<?php include $_SERVER['DOCUMENT_ROOT'] . "/demos-php/inc/config.php"; ?>
<?php $_UNKNOWN['gc_theme_folder'] = "/demos-php/theme-gcwu-fegc"; ?>
<?php $_UNKNOWN['gc_build_folder'] = "/build"; ?>
<?php $_UNKNOWN['gc_bt_fa_filename'] = "index.php"; ?>
<?php $_UNKNOWN['gc_centre_footer_file'] = "/" . $_UNKNOWN['gc_theme_folder'] . "/inc/cont/centre-footer.php"; ?>
<?php $_UNKNOWN['gc_gcnavbar_eng'] = "Government of Canada navigation bar"; ?>
<?php $_UNKNOWN['gc_gcnavbar_fra'] = "Barre de navigation de la gouvernement de Canada"; ?>
<?php $_UNKNOWN['gc_sig_eng'] = "Government of Canada"; ?>
<?php $_UNKNOWN['gc_sig_fra'] = "Gouvernement du Canada"; ?>
<?php $_UNKNOWN['gc_sig_image'] = "sig"; ?>
<?php $_UNKNOWN['gc_gcnb1_href_eng'] = "http://www.canada.gc.ca/menu-eng.html"; ?>
<?php $_UNKNOWN['gc_gcnb1_href_fra'] = "http://www.canada.gc.ca/menu-fra.html"; ?>
<?php $_UNKNOWN['gc_gcnb1_text_eng'] = "Canada.gc.ca"; ?>
<?php $_UNKNOWN['gc_gcnb1_text_fra'] = "Canada.gc.ca"; ?>
<?php $_UNKNOWN['gc_gcnb2_href_eng'] = "http://www.servicecanada.gc.ca/eng/home.shtml"; ?>
<?php $_UNKNOWN['gc_gcnb2_href_fra'] = "http://www.servicecanada.gc.ca/fra/accueil.shtml"; ?>
<?php $_UNKNOWN['gc_gcnb2_text_eng'] = "Services"; ?>
<?php $_UNKNOWN['gc_gcnb2_text_fra'] = "Services"; ?>
<?php $_UNKNOWN['gc_gcnb3_href_eng'] = "http://www.canada.gc.ca/aboutgov-ausujetgouv/depts/menu-eng.html"; ?>
<?php $_UNKNOWN['gc_gcnb3_href_fra'] = "http://www.canada.gc.ca/aboutgov-ausujetgouv/depts/menu-fra.html"; ?>
<?php $_UNKNOWN['gc_gcnb3_text_eng'] = "Departments"; ?>
<?php $_UNKNOWN['gc_gcnb3_text_fra'] = "Ministères"; ?>
<?php $_UNKNOWN['gc_cmblang_href_eng'] = "#"; ?>
<?php $_UNKNOWN['gc_cmblang_href_fra'] = "#"; ?>
<?php $_UNKNOWN['gc_cmblang_title_eng'] = "Français - Version française de cette page"; ?>
<?php $_UNKNOWN['gc_cmblang_title_fra'] = "English - English version of the Web page"; ?>
<?php $_UNKNOWN['gc_cmblang_title_site_eng'] = "English - English version of the Web site"; ?>
<?php $_UNKNOWN['gc_cmblang_title_site_fra'] = "Français - Version française de ce site Web"; ?>
<?php $_UNKNOWN['gc_cmblang_text_eng'] = "Français"; ?>
<?php $_UNKNOWN['gc_cmblang_text_fra'] = "English"; ?>
<?php $_UNKNOWN['gc_wmms_eng'] = "Symbol of the Government of Canada"; ?>
<?php $_UNKNOWN['gc_wmms_fra'] = "Symbole du gouvernement du Canada"; ?>
<?php $_UNKNOWN['gc_site_title_eng'] = "PHP Variant"; ?>
<?php $_UNKNOWN['gc_site_title_fra'] = "Variante pour PHP"; ?>
<?php $_UNKNOWN['gc_banner_href_eng'] = "#"; ?>
<?php $_UNKNOWN['gc_banner_href_fra'] = "#"; ?>
<?php $_UNKNOWN['gc_domain_eng'] = "[www.]mainsite-siteprimaire.gc.ca"; ?>
<?php $_UNKNOWN['gc_domain_fra'] = "[www.]siteprimaire-mainsite.gc.ca"; ?>
<?php $_UNKNOWN['gc_search_eng'] = "Search"; ?>
<?php $_UNKNOWN['gc_search_fra'] = "Recherche"; ?>
<?php $_UNKNOWN['gc_search_label_eng'] = "Search Web site"; ?>
<?php $_UNKNOWN['gc_search_label_fra'] = "Recherchez le site Web"; ?>
<?php $_UNKNOWN['gc_search_file'] = "/" . $_UNKNOWN['gc_theme_folder'] . "/inc/cont/search.php"; ?>
<?php $_UNKNOWN['gc_sitenav_eng'] = "<span>Site </span>menu"; ?>
<?php $_UNKNOWN['gc_sitenav_fra'] = "Menu<span> du site</span>"; ?>
<?php $_UNKNOWN['gc_menuprim'] = "/demos-php/menu/prim-megamenu"; ?>
<?php $_UNKNOWN['gc_bcrumb_eng'] = "Breadcrumb trail"; ?>
<?php $_UNKNOWN['gc_bcrumb_fra'] = "Fil d'Ariane"; ?>
<?php $_UNKNOWN['gc_doc_dates_eng'] = "Date modified:"; ?>
<?php $_UNKNOWN['gc_doc_dates_fra'] = "Date de modification&nbsp;:"; ?>
<?php $_UNKNOWN['gc_doc_version_eng'] = "Version:"; ?>
<?php $_UNKNOWN['gc_doc_version_fra'] = "Version&nbsp;:"; ?>
<?php $_UNKNOWN['gc_sitefooter_eng'] = "Site footer"; ?>
<?php $_UNKNOWN['gc_sitefooter_fra'] = "Pied de page du site"; ?>
<?php $_UNKNOWN['gc_gcfooter_eng'] = "Government of Canada footer"; ?>
<?php $_UNKNOWN['gc_gcfooter_fra'] = "Pied de page du gouvernement du Canada"; ?>
<?php $_UNKNOWN['gc_terms_href_eng'] = "#"; ?>
<?php $_UNKNOWN['gc_terms_href_fra'] = "#"; ?>
<?php $_UNKNOWN['gc_terms_text_eng'] = "Terms and conditions"; ?>
<?php $_UNKNOWN['gc_terms_text_fra'] = "Avis"; ?>
<?php $_UNKNOWN['gc_trans_href_eng'] = "#"; ?>
<?php $_UNKNOWN['gc_trans_href_fra'] = "#"; ?>
<?php $_UNKNOWN['gc_trans_text_eng'] = "Transparency"; ?>
<?php $_UNKNOWN['gc_trans_text_fra'] = "Transparence"; ?>
<?php $_UNKNOWN['gc_trail1_href_eng'] = "http://healthycanadians.gc.ca/index-eng.php"; ?>
<?php $_UNKNOWN['gc_trail1_href_fra'] = "http://canadiensensante.gc.ca/index-fra.php"; ?>
<?php $_UNKNOWN['gc_trail1_text_eng'] = "Health"; ?>
<?php $_UNKNOWN['gc_trail1_text_fra'] = "Santé"; ?>
<?php $_UNKNOWN['gc_trail1_textsub_eng'] = "healthycanadians.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail1_textsub_fra'] = "canadiensensante.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail2_href_eng'] = "http://www.voyage.gc.ca/index-eng.asp"; ?>
<?php $_UNKNOWN['gc_trail2_href_fra'] = "http://www.voyage.gc.ca/index-fra.asp"; ?>
<?php $_UNKNOWN['gc_trail2_text_eng'] = "Travel"; ?>
<?php $_UNKNOWN['gc_trail2_text_fra'] = "Voyage"; ?>
<?php $_UNKNOWN['gc_trail2_textsub_eng'] = "travel.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail2_textsub_fra'] = "voyage.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail3_href_eng'] = "http://www.servicecanada.gc.ca/eng/home.shtml"; ?>
<?php $_UNKNOWN['gc_trail3_href_fra'] = "http://www.servicecanada.gc.ca/fra/accueil.shtml"; ?>
<?php $_UNKNOWN['gc_trail3_text_eng'] = "Service Canada"; ?>
<?php $_UNKNOWN['gc_trail3_text_fra'] = "Service Canada"; ?>
<?php $_UNKNOWN['gc_trail3_textsub_eng'] = "servicecanada.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail3_textsub_fra'] = "servicecanada.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail4_href_eng'] = "http://www.jobbank.gc.ca/intro-eng.aspx"; ?>
<?php $_UNKNOWN['gc_trail4_href_fra'] = "http://www.guichetemplois.gc.ca/Intro-fra.aspx"; ?>
<?php $_UNKNOWN['gc_trail4_text_eng'] = "Jobs"; ?>
<?php $_UNKNOWN['gc_trail4_text_fra'] = "Emplois"; ?>
<?php $_UNKNOWN['gc_trail4_textsub_eng'] = "jobbank.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail4_textsub_fra'] = "guichetemplois.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail5_href_eng'] = "http://actionplan.gc.ca/en"; ?>
<?php $_UNKNOWN['gc_trail5_href_fra'] = "http://plandaction.gc.ca/fr"; ?>
<?php $_UNKNOWN['gc_trail5_text_eng'] = "Economy"; ?>
<?php $_UNKNOWN['gc_trail5_text_fra'] = "Économie"; ?>
<?php $_UNKNOWN['gc_trail5_textsub_eng'] = "actionplan.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail5_textsub_fra'] = "plandaction.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail_canada_href_eng'] = "http://www.canada.gc.ca/menu-eng.html"; ?>
<?php $_UNKNOWN['gc_trail_canada_href_fra'] = "http://www.canada.gc.ca/menu-fra.html"; ?>
<?php $_UNKNOWN['gc_trail_canada_text_eng'] = "Canada.gc.ca"; ?>
<?php $_UNKNOWN['gc_trail_canada_text_fra'] = "Canada.gc.ca"; ?>
<?php $_UNKNOWN['gc_langselect_eng'] = "Language selection links"; ?>
<?php $_UNKNOWN['gc_langselect_fra'] = "Liens de sélection de langue"; ?>
<?php $_UNKNOWN['gc_langalt_eng'] = "fr"; ?>
<?php $_UNKNOWN['gc_langalt_fra'] = "en"; ?>
<?php $_UNKNOWN['gc_hidebtarrow'] = "1"; ?>