<?php $_UNKNOWN['wb_meta_eng'] = "en"; ?>
<?php $_UNKNOWN['wb_meta_fra'] = "fr"; ?>
<?php $_UNKNOWN['wb_meta_deu'] = "de"; ?>
<?php $_UNKNOWN['wb_meta_spa'] = "es"; ?>
<?php $_UNKNOWN['wb_meta_ita'] = "it"; ?>
<?php $_UNKNOWN['wb_meta_por'] = "pt"; ?>
<?php $_UNKNOWN['wb_meta_rus'] = "ru"; ?>
<?php $_UNKNOWN['wb_lang_text_eng'] = "English"; ?>
<?php $_UNKNOWN['wb_lang_text_fra'] = "Français"; ?>
<?php $_UNKNOWN['wb_lang_text_deu'] = "Deutsch"; ?>
<?php $_UNKNOWN['wb_lang_text_spa'] = "Español"; ?>
<?php $_UNKNOWN['wb_lang_text_ita'] = "Italiano"; ?>
<?php $_UNKNOWN['wb_lang_text_por'] = "Português"; ?>
<?php $_UNKNOWN['wb_lang_text_rus'] = "&#1056;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;"; ?>
<?php $_UNKNOWN['wb_sh_link_1_eng'] = "Skip to main content"; ?>
<?php $_UNKNOWN['wb_sh_link_1_fra'] = "Passer au contenu principal"; ?>
<?php $_UNKNOWN['wb_sh_link_2_eng'] = "Skip to secondary menu"; ?>
<?php $_UNKNOWN['wb_sh_link_2_fra'] = "Passer au menu secondaire"; ?>
<?php $_UNKNOWN['wb_sh_link_3_eng'] = "Skip to footer"; ?>
<?php $_UNKNOWN['wb_sh_link_3_fra'] = "Passer au pied de page"; ?>
<?php $_UNKNOWN['wb_sec_eng'] = "Secondary menu"; ?>
<?php $_UNKNOWN['wb_sec_fra'] = "Menu secondaire"; ?>
<?php $_UNKNOWN['wb_sup_eng'] = "Supplemental content"; ?>
<?php $_UNKNOWN['wb_sup_fra'] = "Contenu supplémentaire"; ?>
<?php $_UNKNOWN['wb_foot_eng'] = "Footer"; ?>
<?php $_UNKNOWN['wb_foot_fra'] = "Pied de page"; ?>
<?php $_UNKNOWN['wb_cmblang_title_eng'] = "Français - Version française de cette page"; ?>
<?php $_UNKNOWN['wb_cmblang_title_fra'] = "English - English version of the Web page"; ?>
<?php $_UNKNOWN['wb_cmblang_text_eng'] = "Français"; ?>
<?php $_UNKNOWN['wb_cmblang_text_fra'] = "English"; ?>
<?php $_UNKNOWN['wb_site_title_eng'] = "PHP Variant"; ?>
<?php $_UNKNOWN['wb_site_title_fra'] = "Variante pour PHP"; ?>
<?php $_UNKNOWN['wb_search_eng'] = "Search"; ?>
<?php $_UNKNOWN['wb_search_fra'] = "Recherche"; ?>
<?php $_UNKNOWN['wb_search_label_eng'] = "Search Web site"; ?>
<?php $_UNKNOWN['wb_search_label_fra'] = "Recherchez le site Web"; ?>
<?php $_UNKNOWN['wb_sitenav_eng'] = "Site menu"; ?>
<?php $_UNKNOWN['wb_sitenav_fra'] = "Menu du site"; ?>
<?php $_UNKNOWN['wb_bcrumb_eng'] = "Breadcrumb trail"; ?>
<?php $_UNKNOWN['wb_bcrumb_fra'] = "Fil d'Ariane"; ?>
<?php $_UNKNOWN['wb_doc_dates_eng'] = "Date modified:"; ?>
<?php $_UNKNOWN['wb_doc_dates_fra'] = "Date de modification&nbsp;:"; ?>
<?php $_UNKNOWN['wb_doc_version_eng'] = "Version:"; ?>
<?php $_UNKNOWN['wb_doc_version_fra'] = "Version&nbsp;:"; ?>
<?php $_UNKNOWN['wb_sitefooter_eng'] = "Site footer"; ?>
<?php $_UNKNOWN['wb_sitefooter_fra'] = "Pied de page du site"; ?>