<?php $_UNKNOWN['gcwu_meta_eng'] = "en"; ?>
<?php $_UNKNOWN['gcwu_meta_fra'] = "fr"; ?>
<?php $_UNKNOWN['gcwu_meta_deu'] = "de"; ?>
<?php $_UNKNOWN['gcwu_meta_spa'] = "es"; ?>
<?php $_UNKNOWN['gcwu_meta_ita'] = "it"; ?>
<?php $_UNKNOWN['gcwu_meta_por'] = "pt"; ?>
<?php $_UNKNOWN['gcwu_meta_rus'] = "ru"; ?>
<?php $_UNKNOWN['gcwu_lang_text_eng'] = "English"; ?>
<?php $_UNKNOWN['gcwu_lang_text_fra'] = "Français"; ?>
<?php $_UNKNOWN['gcwu_lang_text_deu'] = "Deutsch"; ?>
<?php $_UNKNOWN['gcwu_lang_text_spa'] = "Español"; ?>
<?php $_UNKNOWN['gcwu_lang_text_ita'] = "Italiano"; ?>
<?php $_UNKNOWN['gcwu_lang_text_por'] = "Português"; ?>
<?php $_UNKNOWN['gcwu_lang_text_rus'] = "&#1056;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;"; ?>
<?php $_UNKNOWN['gcwu_sh_link_1_eng'] = "Skip to main content"; ?>
<?php $_UNKNOWN['gcwu_sh_link_1_fra'] = "Passer au contenu principal"; ?>
<?php $_UNKNOWN['gcwu_sh_link_2_eng'] = "Skip to side navigation"; ?>
<?php $_UNKNOWN['gcwu_sh_link_2_fra'] = "Passer à la navigation latérale"; ?>
<?php $_UNKNOWN['gcwu_sh_link_3_eng'] = "Skip to footer"; ?>
<?php $_UNKNOWN['gcwu_sh_link_3_fra'] = "Passer au pied de page"; ?>
<?php $_UNKNOWN['gcwu_left_col_eng'] = "Side navigation (left column)"; ?>
<?php $_UNKNOWN['gcwu_left_col_fra'] = "Navigation latérale (colonne gauche)"; ?>
<?php $_UNKNOWN['gcwu_right_col_eng'] = "Supplemental content (right column)"; ?>
<?php $_UNKNOWN['gcwu_right_col_fra'] = "Contenu supplémentaire (colonne droite)"; ?>
<?php $_UNKNOWN['gcwu_foot_eng'] = "Footer"; ?>
<?php $_UNKNOWN['gcwu_foot_fra'] = "Pied de page"; ?>