<?php include $_SERVER['DOCUMENT_ROOT'] . "/demos-php/inc/config.php"; ?>
<?php $_UNKNOWN['gcwu_theme_folder'] = "/demos-php/theme-gcwu-fegc"; ?>
<?php $_UNKNOWN['gcwu_build_folder'] = "/build"; ?>
<?php $_UNKNOWN['gcwu_bt_fa_filename'] = "index.php"; ?>
<?php $_UNKNOWN['gcwu_centre_footer_file'] = "/" . $_UNKNOWN['gcwu_theme_folder'] . "/inc/cont/centre-footer.php"; ?>
<?php $_UNKNOWN['gcwu_gcnavbar_eng'] = "Government of Canada navigation bar"; ?>
<?php $_UNKNOWN['gcwu_gcnavbar_fra'] = "Barre de navigation de la gouvernement de Canada"; ?>
<?php $_UNKNOWN['gcwu_sig_eng'] = "Government of Canada"; ?>
<?php $_UNKNOWN['gcwu_sig_fra'] = "Gouvernement du Canada"; ?>
<?php $_UNKNOWN['gcwu_sig_image'] = "sig"; ?>
<?php $_UNKNOWN['gcwu_gcnb1_href_eng'] = "http://www.canada.gc.ca/menu-eng.html"; ?>
<?php $_UNKNOWN['gcwu_gcnb1_href_fra'] = "http://www.canada.gc.ca/menu-fra.html"; ?>
<?php $_UNKNOWN['gcwu_gcnb1_text_eng'] = "Canada.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_gcnb1_text_fra'] = "Canada.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_gcnb2_href_eng'] = "http://www.servicecanada.gc.ca/eng/home.shtml"; ?>
<?php $_UNKNOWN['gcwu_gcnb2_href_fra'] = "http://www.servicecanada.gc.ca/fra/accueil.shtml"; ?>
<?php $_UNKNOWN['gcwu_gcnb2_text_eng'] = "Services"; ?>
<?php $_UNKNOWN['gcwu_gcnb2_text_fra'] = "Services"; ?>
<?php $_UNKNOWN['gcwu_gcnb3_href_eng'] = "http://www.canada.gc.ca/aboutgov-ausujetgouv/depts/menu-eng.html"; ?>
<?php $_UNKNOWN['gcwu_gcnb3_href_fra'] = "http://www.canada.gc.ca/aboutgov-ausujetgouv/depts/menu-fra.html"; ?>
<?php $_UNKNOWN['gcwu_gcnb3_text_eng'] = "Departments"; ?>
<?php $_UNKNOWN['gcwu_gcnb3_text_fra'] = "Ministères"; ?>
<?php $_UNKNOWN['wb_cmblang_href_eng'] = "#"; ?>
<?php $_UNKNOWN['wb_cmblang_href_fra'] = "#"; ?>
<?php $_UNKNOWN['wb_cmblang_title_site_eng'] = "English - English version of the Web site"; ?>
<?php $_UNKNOWN['wb_cmblang_title_site_fra'] = "Français - Version française de ce site Web"; ?>
<?php $_UNKNOWN['gcwu_wmms_eng'] = "Symbol of the Government of Canada"; ?>
<?php $_UNKNOWN['gcwu_wmms_fra'] = "Symbole du gouvernement du Canada"; ?>
<?php $_UNKNOWN['gcwu_banner_href_eng'] = "#"; ?>
<?php $_UNKNOWN['gcwu_banner_href_fra'] = "#"; ?>
<?php $_UNKNOWN['gcwu_domain_eng'] = "[www.]mainsite-siteprimaire.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_domain_fra'] = "[www.]siteprimaire-mainsite.gc.ca"; ?>
<?php $_UNKNOWN['wb_search_file'] = "/" . $_UNKNOWN['gcwu_theme_folder'] . "/inc/cont/search.php"; ?>
<?php $_UNKNOWN['gcwu_menuprim'] = "/demos-php/menu/prim-megamenu"; ?>
<?php $_UNKNOWN['gcwu_gcfooter_eng'] = "Government of Canada footer"; ?>
<?php $_UNKNOWN['gcwu_gcfooter_fra'] = "Pied de page du gouvernement du Canada"; ?>
<?php $_UNKNOWN['gcwu_terms_href_eng'] = "#"; ?>
<?php $_UNKNOWN['gcwu_terms_href_fra'] = "#"; ?>
<?php $_UNKNOWN['gcwu_terms_text_eng'] = "Terms and conditions"; ?>
<?php $_UNKNOWN['gcwu_terms_text_fra'] = "Avis"; ?>
<?php $_UNKNOWN['gcwu_trans_href_eng'] = "#"; ?>
<?php $_UNKNOWN['gcwu_trans_href_fra'] = "#"; ?>
<?php $_UNKNOWN['gcwu_trans_text_eng'] = "Transparency"; ?>
<?php $_UNKNOWN['gcwu_trans_text_fra'] = "Transparence"; ?>
<?php $_UNKNOWN['gcwu_trail1_href_eng'] = "http://healthycanadians.gc.ca/index-eng.php"; ?>
<?php $_UNKNOWN['gcwu_trail1_href_fra'] = "http://canadiensensante.gc.ca/index-fra.php"; ?>
<?php $_UNKNOWN['gcwu_trail1_text_eng'] = "Health"; ?>
<?php $_UNKNOWN['gcwu_trail1_text_fra'] = "Santé"; ?>
<?php $_UNKNOWN['gcwu_trail1_textsub_eng'] = "healthycanadians.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail1_textsub_fra'] = "canadiensensante.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail2_href_eng'] = "http://www.voyage.gc.ca/index-eng.asp"; ?>
<?php $_UNKNOWN['gcwu_trail2_href_fra'] = "http://www.voyage.gc.ca/index-fra.asp"; ?>
<?php $_UNKNOWN['gcwu_trail2_text_eng'] = "Travel"; ?>
<?php $_UNKNOWN['gcwu_trail2_text_fra'] = "Voyage"; ?>
<?php $_UNKNOWN['gcwu_trail2_textsub_eng'] = "travel.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail2_textsub_fra'] = "voyage.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail3_href_eng'] = "http://www.servicecanada.gc.ca/eng/home.shtml"; ?>
<?php $_UNKNOWN['gcwu_trail3_href_fra'] = "http://www.servicecanada.gc.ca/fra/accueil.shtml"; ?>
<?php $_UNKNOWN['gcwu_trail3_text_eng'] = "Service Canada"; ?>
<?php $_UNKNOWN['gcwu_trail3_text_fra'] = "Service Canada"; ?>
<?php $_UNKNOWN['gcwu_trail3_textsub_eng'] = "servicecanada.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail3_textsub_fra'] = "servicecanada.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail4_href_eng'] = "http://www.jobbank.gc.ca/intro-eng.aspx"; ?>
<?php $_UNKNOWN['gcwu_trail4_href_fra'] = "http://www.guichetemplois.gc.ca/Intro-fra.aspx"; ?>
<?php $_UNKNOWN['gcwu_trail4_text_eng'] = "Jobs"; ?>
<?php $_UNKNOWN['gcwu_trail4_text_fra'] = "Emplois"; ?>
<?php $_UNKNOWN['gcwu_trail4_textsub_eng'] = "jobbank.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail4_textsub_fra'] = "guichetemplois.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail5_href_eng'] = "http://actionplan.gc.ca/en"; ?>
<?php $_UNKNOWN['gcwu_trail5_href_fra'] = "http://plandaction.gc.ca/fr"; ?>
<?php $_UNKNOWN['gcwu_trail5_text_eng'] = "Economy"; ?>
<?php $_UNKNOWN['gcwu_trail5_text_fra'] = "Économie"; ?>
<?php $_UNKNOWN['gcwu_trail5_textsub_eng'] = "actionplan.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail5_textsub_fra'] = "plandaction.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail_canada_href_eng'] = "http://www.canada.gc.ca/menu-eng.html"; ?>
<?php $_UNKNOWN['gcwu_trail_canada_href_fra'] = "http://www.canada.gc.ca/menu-fra.html"; ?>
<?php $_UNKNOWN['gcwu_trail_canada_text_eng'] = "Canada.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_trail_canada_text_fra'] = "Canada.gc.ca"; ?>
<?php $_UNKNOWN['gcwu_langselect_eng'] = "Language selection links"; ?>
<?php $_UNKNOWN['gcwu_langselect_fra'] = "Liens de sélection de langue"; ?>
<?php $_UNKNOWN['gcwu_langalt_eng'] = "fr"; ?>
<?php $_UNKNOWN['gcwu_langalt_fra'] = "en"; ?>
<?php $_UNKNOWN['gcwu_hidebtarrow'] = "1"; ?>